### ISSUE TITLE
Code doesn't follow tutorial

### ISSUE THREAD

**Issue by matthewboman** [andrecastelo/example-api#1]
I've been following [your tutorial](https://www.toptal.com/laravel/restful-laravel-api-tutorial) but sometimes the code in it is different from what's in this repository. For example [RegisterController](https://github.com/andrecastelo/example-api/blob/master/app/Http/Controllers/Auth/RegisterController.php) has no register function.

I was looking for the routes.php to see how you handle registration, but saw it listed in your .gitignore.

**Comment by andrecastelo** [comment]
Hey @crashspringfield ! The thing is - the register method is added via the [RegistersUsers](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Auth/RegistersUsers.php) trait, that I chose to reuse.

The routes are included in [the routes/api.php file](https://github.com/andrecastelo/example-api/blob/master/routes/api.php). The `routes.php` was split into `routes/web.php` and `routes/api.php` in Laravel 5.4.

Let me know if this does not work for you.

**Comment by thetnaingtn** [comment]
I want to ask some question.Where to write registered function in RegisterController or in RegistersUsers trait
