### ISSUE TITLE
Register API is not working

### ISSUE THREAD

**Issue by saravanaams** [andrecastelo/example-api#2]
Hi,

I found this one is very useful.And i'm new to laravel.
Login API is working fine.But Register API is not working.It's returning response code "200".But record is not inserting.
![screenshot from 2018-01-11 22-25-21](https://user-images.githubusercontent.com/8102616/34836583-5534eafa-f71e-11e7-873e-e0971c541649.png)
After submitting i'm getting this respose in body.

And also i need to add CORS in this.

COuld you please help me out to add CORS middleware in this

**Comment by andrecastelo** [comment]
You need to add the header:

```
Content-Type: application/json
```

To handle CORS, you can simply add the package https://github.com/barryvdh/laravel-cors
